version: "3.7"
services:
  postgres:
    container_name: 'to-do-postgres'
    image: 'postgres:15.2'
    restart: always
    ports:
      - '5454:5432'
    environment:
      - 'POSTGRES_USER=username'
      - 'POSTGRES_DB=to_do'
      - 'POSTGRES_PASSWORD=password'